apiVersion: v1
kind: ReplicationController 
metadata:
  name: my-rc
  labels:
    name: my-rc

spec:  
  template:
    metadata:
      name: ihos-pod
      labels:
        name: ihos-pod
        type: Pod 

    spec:
      containers:
        - name: ihos-pod
          image: ihoslav/thetech-image:v1
          ports:
            - containerPort: 3000
  replicas: 3